services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emit-web-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: emit-web-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start